name: Generate and Deploy

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 确保有写入权限

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: master  # 明确检出 master 分支

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies and run scripts
      run: |
        for dir in scripts/*/; do
          if [ -f "$dir/requirements.txt" ] && [ -f "$dir/main.py" ]; then
            echo "Processing $dir"
            python -m pip install --upgrade pip
            pip install -r "$dir/requirements.txt"
            python "$dir/main.py"
          fi
        done

    - name: Commit and Push to Master
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ./docs
        git commit -m "Auto-update docs via GitHub Actions"
        git push origin master